Ikbal caprover
jabardigitalservice/pikobar-logistik-api pull request #259
Opened 2021-04-22 04:14 UTC by mhdikbal

Bang Rindi yang baik,
berikut satu lagi PR, penambahan file yaitu;

1. captain-defenition
2. Dockerfile-caprover

2021-04-22 04:23 UTC, rindibudiaramdhan approved these changes
ada beberapa kondisi yang masih khusus di staging yang saya sesuaikan dahulu.
sisanya aman.

2021-04-27 06:30 UTC, mhdikbal commented
1. change image docker from apache to alpine
2. add captain-defenition

2021-04-27 06:52 UTC, yohang88 requested changes
Ini kok banyak sekali. Tolong disederhanakan, seharusnya cukup 1 Dockerfile saja.

2021-04-27 07:02 UTC, mhdikbal commented
Sudah aku sederhanakan, mas Yoga, saat ini terdapat satu file Dockerfile.

2021-04-27 07:17 UTC, yohang88 commented
> Sudah aku sederhanakan, mas Yoga, saat ini terdapat satu file Dockerfile.

Itu masih ada beberapa entrypoint; ada folder `docker` ada folder `docker-config`, ini juga perlu disederhanakan.

2021-04-27 07:23 UTC, mhdikbal commented
> > Sudah aku sederhanakan, mas Yoga, saat ini terdapat satu file Dockerfile.
> 
> Itu masih ada beberapa entrypoint; ada folder `docker` ada folder `docker-config`, ini juga perlu disederhanakan.

untuk folder juga sudah aku sederhanakan dengan menghapus folder docker, saat ini seluruh configuration Dockerfile ada di directory docker-config.

2021-04-27 07:23 UTC, mhdikbal commented
> > Sudah aku sederhanakan, mas Yoga, saat ini terdapat satu file Dockerfile.
> 
> Itu masih ada beberapa entrypoint; ada folder `docker` ada folder `docker-config`, ini juga perlu disederhanakan.

untuk folder juga sudah aku sederhanakan dengan menghapus folder docker, saat ini seluruh configuration Dockerfile ada di directory docker-config.

2021-04-27 07:35 UTC, yohang88 requested changes
Cek cek @mhdikbal

2021-04-27 07:35 UTC, yohang88 commented on 1
> +
Ini isi file apa ya? Kan sudah ada Dockerfile di bawah

2021-04-27 07:35 UTC, yohang88 commented on docker-start.sh
> +    php /var/www/artisan queue:work redis --verbose --daemon
Ini dipakai? Redis ini apa ya?

2021-04-27 07:35 UTC, yohang88 commented on docker-config/php.ini
> +date.timezone="Asia/Jakarta"
Ini tidak boleh diset timezone Asia/Jakarta. Aplikasi harus bisa dideploy dimana saja dalam konfigurasi UTC, terlepas dari timezone manapun.

2021-04-27 07:35 UTC, yohang88 commented on 1
> +CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
Ini yang dipakai yang mana? Entrypoint atau CMD?

2021-04-27 07:35 UTC, yohang88 commented on docker-start.sh
> +#!/usr/bin/env bash
Ini docker-start.sh kapan dijalankan? Kan pakai supervisor.

2021-04-27 07:40 UTC, mhdikbal commented on 1
> +CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
ENTRYPOINT nya sudah aku command, nga di pake lagi itu mas

2021-04-27 07:46 UTC, mhdikbal commented on docker-config/php.ini
> +date.timezone="Asia/Jakarta"
sudah aku remove, mas

2021-04-27 07:47 UTC, mhdikbal commented on docker-start.sh
> +    php /var/www/artisan queue:work redis --verbose --daemon
ini nga di pake, mas

2021-04-27 07:47 UTC, mhdikbal commented on docker-start.sh
> +#!/usr/bin/env bash
sudah aku remove, mas

2021-04-27 07:51 UTC, yohang88 requested changes
Cek cek lagi @mhdikbal

2021-04-27 07:51 UTC, yohang88 commented on Dockerfile
> +        php7-ssh2 \
Ini untuk apa ya?

2021-04-27 07:51 UTC, yohang88 commented on Dockerfile
> +		php7 \
Ini di atas ada install packages `php` dan di sini ada `php7` apa bedanya?

2021-04-27 07:51 UTC, yohang88 commented on Dockerfile
> +RUN mv /etc/php7/conf.d/ssh2.ini /etc/php7/conf.d/ssh2.old
ini modul untuk apa kok pakai SSH ?

2021-04-27 07:51 UTC, yohang88 commented on Dockerfile
> +RUN php artisan storage:link
Ini dipakai untuk apa? Seharusnya file ga boleh disimpan di container, tapi harus di object storage (contoh AWS S3)

2021-04-27 08:05 UTC, mhdikbal commented on Dockerfile
> +        php7-ssh2 \
package dari php yang diperlukan oleh aplikasi, mas. ada berapa package yang aku tambahkan dikarenakan saat melakukan build d caprover itu memunculkan error, dimana error nya adalah package tidak ada.

2021-04-27 08:33 UTC, mhdikbal commented on Dockerfile
> +RUN php artisan storage:link
ini sudah aku hapus, mas. Benar Mas, semestinya menyimpan file tersebut di S3, rackspace. 
https://laravel.com/docs/5.1/filesystem

2021-04-27 08:44 UTC, mhdikbal commented on Dockerfile
> +RUN mv /etc/php7/conf.d/ssh2.ini /etc/php7/conf.d/ssh2.old
ini juga sudah aku hapus, mas..

2021-04-27 08:45 UTC, mhdikbal commented on Dockerfile
> +		php7 \
```
RUN echo "https://dl.bintray.com/php-alpine/v3.10/php-7.4" >> /etc/apk/repositories

# Install packages
RUN apk add php php-fpm php-opcache php-openssl php-curl php-gd \
    nginx supervisor curl
```
    
   pada baris d atas, berfungsi untuk melakukan

1. Menambahkan repository php 7.4 di docker alpine
2. Melakukan instalasi php, php-fpm

maaf aku keliru untuk package tersebut, semestinya tidak aku tambahkan lagi php7 dibagian 
`RUN apk add \`
oleh karena itu, php7 tersebut sudah aku hapus

2021-04-27 08:46 UTC, mhdikbal commented
Sudah dilakukan perbaikan dan perubahan pada Dockerfile, dan telah dijalankan di caprover local. 
<img width="1440" alt="Screen Shot 2021-04-27 at 15 46 02" src="https://user-images.githubusercontent.com/58279387/116213083-ae280980-a76f-11eb-809a-050685bd02d1.png">

2021-04-27 08:56 UTC, mhdikbal commented
aku coba juga build di caprover dengan branch ikbal-caprover.

<img width="1423" alt="Screen Shot 2021-04-27 at 15 55 49" src="https://user-images.githubusercontent.com/58279387/116214587-0b708a80-a771-11eb-851b-71773728056d.png">

2021-04-27 21:28 UTC, yohang88 requested changes
Cek cek

2021-04-27 21:28 UTC, yohang88 commented on Dockerfile
> +        php7-ssh2 \
package `ssh2` ini aku yakin ga dipakai di aplikasi sih. bisa dibantu konfirm @rindibudiaramdhan ?

2021-04-27 21:28 UTC, yohang88 commented on Dockerfile
> +        npm
Ini kenapa juga ada `npm` ? Kan ini bukan frontend.

2021-04-28 01:20 UTC, mhdikbal commented on Dockerfile
> +        npm
Baik Mas Yoga, untuk beberapa package sudah aku hapus, diantara paket tersebut memang ada beberapa paket yang diperlukan, jika tidak disertakan paket tersebut memunculkan error saat build

```
Problem 1
    - Installation request for phpoffice/phpspreadsheet 1.11.0 -> satisfiable by phpoffice/phpspreadsheet[1.11.0].
    - phpoffice/phpspreadsheet 1.11.0 requires ext-ctype * -> the requested PHP extension ctype is missing from your system.
  Problem 2
    - phpoffice/phpspreadsheet 1.11.0 requires ext-ctype * -> the requested PHP extension ctype is missing from your system.
    - maatwebsite/excel 3.1.19 requires phpoffice/phpspreadsheet ^1.10 -> satisfiable by phpoffice/phpspreadsheet[1.11.0].
    - Installation request for maatwebsite/excel 3.1.19 -> satisfiable by maatwebsite/excel[3.1.19].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php7/php.ini
    - /etc/php7/conf.d/00_curl.ini
    - /etc/php7/conf.d/00_gd.ini
    - /etc/php7/conf.d/00_iconv.ini
    - /etc/php7/conf.d/00_json.ini
    - /etc/php7/conf.d/00_mbstring.ini
    - /etc/php7/conf.d/00_opcache.ini
    - /etc/php7/conf.d/00_openssl.ini
    - /etc/php7/conf.d/00_pdo.ini
    - /etc/php7/conf.d/00_pdo_sqlite.ini
    - /etc/php7/conf.d/00_xml.ini
    - /etc/php7/conf.d/01_dom.ini
    - /etc/php7/conf.d/01_mysqlnd.ini
    - /etc/php7/conf.d/01_phar.ini
    - /etc/php7/conf.d/20_pdo_mysql.ini
    - /etc/php7/conf.d/custom.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

{"code":2,"message":"The command '/bin/sh -c composer install' returned a non-zero code: 2"}
The command '/bin/sh -c composer install' returned a non-zero code: 2
Build has failed!
----------------------
Deploy failed!
Error: {"code":2,"message":"The command '/bin/sh -c composer install' returned a non-zero code: 2"}
The command '/bin/sh -c composer install' returned a non-zero code: 2
```

2021-04-30 01:25 UTC, mhdikbal commented
mas @yohang88 , apakah ada yang diperbaiki lagi?

2021-04-30 03:13 UTC, yohang88 requested changes
Diskusi lagi @mhdikbal @rindibudiaramdhan

2021-04-30 03:13 UTC, yohang88 commented on Dockerfile
> +CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
Jadi ingat, ini ga dibuat sesuai diskusi tim backend reservasi Command Center? Yang memungkinkan 1 Dockerfile bisa digunakan untuk running sebagai web app, juga bisa bisa dipilih running sebagai queue worker.

2021-04-30 03:39 UTC, smilelikeshit commented on Dockerfile
> +RUN apk add composer
kalau install by repo nanti kita ga tau versi berapa yang ke install. bisa pake pendekatan dari ini. fungsinya agar kita tau versi berapa yang terinstall. mengingat komponen composer ini wajib untuk package manager di php. https://github.com/jabardigitalservice/pikobar-labkes/blob/development/backend/Dockerfile.jacloud

2021-04-30 03:41 UTC, smilelikeshit commented on Dockerfile
> +CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
referensi nya bisa pake ini @mhdikbal  
https://laravel-news.com/laravel-scheduler-queue-docker

2021-04-30 03:53 UTC, yohang88 commented on Dockerfile
> +CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
@smilelikeshit nampaknya sekalian bisa jadi standar Dockerfile untuk Laravel

2021-04-30 03:53 UTC, yohang88 commented on Dockerfile
> +RUN apk add composer
Dan better dibuat multistage build, lumayan mengurangi ukuran image size Docker 😁

2021-04-30 07:11 UTC, smilelikeshit commented on Dockerfile
> +CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
iya mas setuju sekali. @yohang88  bisa di inisiasi sama ikbal untuk perubahan. learning sekaligus ada use casenya :dancers:

2021-05-04 01:27 UTC, mhdikbal commented
mang @rindibudiaramdhan , aku sudah melakukan create Dockerfile sesuai dengan pendekatan 
https://github.com/jabardigitalservice/pikobar-labkes/blob/development/backend/Dockerfile.jacloud
saat ini, status build na success, namun aplikasi tidak dapat diakses.
Logs dari caprover na
```
021-05-03T05:34:32.197675648Z Discovered Package: tymon/jwt-auth
2021-05-03T05:34:32.197761816Z Package manifest generated successfully.
2021-05-03T05:34:32.207536931Z Generated optimized autoload files containing 4481 classes
2021-05-03T05:34:32.322703089Z Configuration cache cleared!
2021-05-03T05:34:32.442245951Z Application cache cleared!
2021-05-03T05:34:32.557450467Z Route cache cleared!
2021-05-03T05:34:32.770968031Z Error: could not read config file /etc/supervisord.conf
2021-05-03T05:34:32.770985024Z For help, use /usr/bin/supervisord -h
```

sementara itu, aku coba debug, apakah supervisord.conf ini tercopy, 
![photo6089276135893479016](https://user-images.githubusercontent.com/58279387/116951612-8a564d80-acb2-11eb-8f3f-5bc169188000.jpg)

dari debug di atas, file supervisord.conf na tercopy.

2021-05-04 03:07 UTC, mhdikbal commented
<img width="682" alt="Screen Shot 2021-05-04 at 10 06 30" src="https://user-images.githubusercontent.com/58279387/116956802-6a2d8b00-acc0-11eb-8c2b-eea39bd2b404.png">
maaf, aku keliru mang @rindibudiaramdhan , sekarang sudah success d build en dapat d akses aplikasi tersebut

2021-05-04 03:16 UTC, mhdikbal commented
![Uploading Screen Shot 2021-05-04 at 10.16.17.png…]()

2021-05-04 03:18 UTC, mhdikbal commented
<img width="915" alt="Screen Shot 2021-05-04 at 10 18 34" src="https://user-images.githubusercontent.com/58279387/116957462-1754d300-acc2-11eb-9e4a-28e45ae6df33.png">

2021-05-04 04:07 UTC, yohang88 requested changes
@mhdikbal @rindibudiaramdhan kemarin saya lupa nulis dimana, sebaiknya dockerfile/entrypoint-nya ditambahkan conditional yang running container sebagai app vs sebagai queue worker itu (seperti diskusi di project reservasi). Tolong ditambahkan dulu ya.

2021-05-04 04:20 UTC, mhdikbal commented
barusan aku coba d local, sudah aku tambahkan di entrypoint 

```
#!/bin/sh
app=${DOCKER_APP:-app}

if [ "$app" = "app" ]; then

    echo "Running the app..."
    /usr/bin/supervisord -c /etc/supervisord.conf

elif [ "$app" = "queue" ]; then

    echo "Running the queue..."
    php artisan queue:work --queue=default --sleep=3 --tries=3

else
    echo "Could not match the container app \"$app\""
    exit 1
fi

php composer.phar dump-autoload
php artisan config:clear
php artisan cache:clear
php artisan route:clear
#php backend/artisan migrate --no-interaction -vvv --force

/usr/bin/supervisord
```

```
2021-05-04T04:18:36.146091755Z Running the app...
2021-05-04T04:18:36.385492230Z 2021-05-04 04:18:36,385 INFO supervisord started with pid 7
2021-05-04T04:18:37.391925214Z 2021-05-04 04:18:37,389 INFO spawned: 'nginx' with pid 9
2021-05-04T04:18:37.392047910Z 2021-05-04 04:18:37,391 INFO spawned: 'php-fpm' with pid 10
2021-05-04T04:18:37.441784844Z [04-May-2021 04:18:37] NOTICE: fpm is running, pid 10
2021-05-04T04:18:37.518047164Z [04-May-2021 04:18:37] NOTICE: ready to handle connections
2021-05-04T04:18:38.520274731Z 2021-05-04 04:18:38,519 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-04T04:18:38.520302402Z 2021-05-04 04:18:38,519 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-04T04:18:49.569349498Z 10.0.0.2 - - [04/May/2021:04:18:49 +0000] "GET /api/v1/ping HTTP/1.1" 200 43 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" "-" 0.027 0.024 . -
2021-05-04T04:18:49.628214289Z 10.0.0.2 - - [04/May/2021:04:18:49 +0000] "GET /favicon.ico HTTP/1.1" 200 0 "http://192.168.1.11:8080/api/v1/ping" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" "-" 0.000 - . -
2021-05-04T04:18:51.071902143Z 10.0.0.2 - - [04/May/2021:04:18:51 +0000] "GET /api/v1/ping HTTP/1.1" 200 43 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" "-" 0.018 0.016 . -
2021-05-04T04:18:51.122248053Z 10.0.0.2 - - [04/May/2021:04:18:51 +0000] "GET /favicon.ico HTTP/1.1" 200 0 "http://192.168.1.11:8080/api/v1/ping" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" "-" 0.000 - . -
```

<img width="1074" alt="Screen Shot 2021-05-04 at 11 20 21" src="https://user-images.githubusercontent.com/58279387/116960489-b978b900-acca-11eb-9535-6af39e975b93.png">

2021-05-04 04:22 UTC, mhdikbal commented
barusan di build d https://captain.rover.digitalservice.id/#/apps/details/pikobar-logistik-api

<img width="1440" alt="Screen Shot 2021-05-04 at 11 22 14" src="https://user-images.githubusercontent.com/58279387/116960565-fd6bbe00-acca-11eb-8367-95ad76aa25ed.png">

2021-05-04 04:26 UTC, yohang88 approved these changes

2021-05-04 04:26 UTC, merged