Tracking modification
jabardigitalservice/pikobar-logistik-api pull request #279
Opened 2021-05-18 05:16 UTC by rindibudiaramdhan

## API Tracking
- Status Code 200 to Response Enum

## API Tracking Detail
- Status Code 200 to Response Enum

## API Tracking Logistic Request
- API yang digunakan untuk mendapatkan daftar Barang di Tahapan Permohonan Masuk

## API Tracking Logistic Recommendation
- API yang digunakan untuk mendapatkan daftar Barang di Tahapan Rekomendasi Salur

## API Tracking Logistic Finalization
- API yang digunakan untuk mendapatkan daftar Barang di Tahapan Realisasi Salur

## API Tracking Logistic Outbound
- API yang digunakan untuk mendapatkan daftar Barang di Tahapan Barang Didistribusikan

2021-05-18 10:33 UTC, aldidoanta requested changes

2021-05-18 10:33 UTC, aldidoanta commented on app/Applicant.php
> +        $status = $value == ApplicantStatusEnum::not_verified() ? LogisticRequestEnum::not_verified() : ($value == ApplicantStatusEnum::verified() ? LogisticRequestEnum::verified() : ($value == Appli
Kang @rindibudiaramdhan kalau logic ini diubah ke dalam bentuk `switch` gimana kang? Apakah mungkin jadi lebih mudah dibaca?

```php
switch($value) {
    case ApplicantStatusEnum::not_verified():
        $status = LogisticRequestEnum::not_verified();
        break;
    case ApplicantStatusEnum::verified():
        // ...
        break;
}
```

2021-05-18 10:33 UTC, aldidoanta commented on app/Enums/LogisticRequestEnum.php
> +    public static function not_yet_verify(): LogisticRequestEnum
Kang @rindibudiaramdhan mau usul kang. Mungkin lebih cocok kalau nama enumnya diubah jadi `not_yet_verified` (passive tense). Soalnya penamaan enum di bawah line ini pakai passive tense juga kan ya.

Misalnya `not_verified`, `approval_rejected`

2021-05-18 10:33 UTC, aldidoanta commented on app/Enums/LogisticRequestEnum.php
> +    public static function not_yet_approve(): LogisticRequestEnum
Yang ini juga sama kang, gimana kalau penamaannya pakai passive tense juga, jadi `not_yet_approved`?

2021-05-18 10:35 UTC, rindibudiaramdhan commented on app/Applicant.php
> +        $status = $value == ApplicantStatusEnum::not_verified() ? LogisticRequestEnum::not_verified() : ($value == ApplicantStatusEnum::verified() ? LogisticRequestEnum::verified() : ($value == Appli
thats nice kang @aldidoanta 
aku ubah ya kang.

2021-05-18 10:40 UTC, ayocodingit commented on app/Http/Controllers/API/v1/TrackController.php
> +        if ($request->route()->named('finalization')) {
kang @rindibudiaramdhan sebaiknya ini kalau beda function agar mudah di pahami,  :smile:

2021-05-18 10:40 UTC, ayocodingit commented on app/Http/Controllers/API/v1/TrackController.php
> +        $outbound = Outbound::select('lo_id', 'whs_name', 'pic_name', 'pic_handphone', 'map_url')
kang @rindibudiaramdhan kalau outbound dan outbound detail itu ada relasi nya gak kang ?
kalau ada boleh digunakan append atau gunakan with :smile:

2021-05-18 10:42 UTC, ayocodingit commented on app/Enums/LogisticRequestEnum.php
> +    public static function not_yet_verify(): LogisticRequestEnum
sebagaiknya gunakan uppercase saja karena enum ini sebenernya pengganti constant :smile:

2021-05-18 10:49 UTC, rindibudiaramdhan commented on app/Http/Controllers/API/v1/TrackController.php
> +        $outbound = Outbound::select('lo_id', 'whs_name', 'pic_name', 'pic_handphone', 'map_url')
ada kang. nah ini saya tidak gunakan append atau with karena mau ada paginationnya. baiknya bagaimana ya?

2021-05-18 10:50 UTC, rindibudiaramdhan commented on app/Enums/LogisticRequestEnum.php
> +    public static function not_yet_verify(): LogisticRequestEnum
jadi best nya uppercase atau lowercase?
saya lihat di dokumentasinya lowercase sih.

2021-05-18 10:54 UTC, rindibudiaramdhan commented on app/Http/Controllers/API/v1/TrackController.php
> +        if ($request->route()->named('finalization')) {
done kang @ayocodingit

2021-05-18 11:18 UTC, rachadiannovansyah commented on app/Applicant.php
> +                $value = '';
kang apakah ini bener untuk defaultnya pake `$value`? bukan $status 🏋️😂

2021-05-19 00:08 UTC, ayocodingit commented on app/Http/Controllers/API/v1/TrackController.php
> +        if ($request->route()->named('recommendation')) {
Ini sebaiknya dibeda function atau endpoint kang biar enak di baca 😁

2021-05-19 00:08 UTC, ayocodingit commented on app/Http/Controllers/API/v1/TrackController.php
> +        $outbound = Outbound::select('lo_id', 'whs_name', 'pic_name', 'pic_handphone', 'map_url')
Oh ngejar paginate nya yang boleh dipelajari kang teknik ini 😁
https://laravel.com/docs/8.x/controllers#restful-nested-resources

Jadi sebaiknya beda endpoint nanti hasilnya kurang lebih seperti ini 

`/photos/{photo}/comments/{comment}`

2021-05-19 01:16 UTC, ayocodingit commented on app/Enums/LogisticRequestEnum.php
> +    public static function not_yet_verify(): LogisticRequestEnum
hmm masih perlu di sepakati yang best nya yang mana :+1: untuk sekarang gpp kang @rindibudiaramdhan

2021-05-19 05:14 UTC, rindibudiaramdhan commented on app/Http/Controllers/API/v1/TrackController.php
> +        $outbound = Outbound::select('lo_id', 'whs_name', 'pic_name', 'pic_handphone', 'map_url')
oke sudah saya pisah ya.
di `/tracking/{id}/logistic-outbound`
dan `/tracking/{id}/logistic-outbound/{loId}`

2021-05-19 05:17 UTC, rindibudiaramdhan commented on app/Applicant.php
> +                $value = '';
done ya nuhuun teliti pisan

2021-05-19 06:04 UTC, ayocodingit commented on app/Http/Controllers/API/v1/TrackController.php
> +        $outboundDetail = OutboundDetail::query()
ini boleh di hapus yah karena udh di pindahkan :smile:

2021-05-19 06:16 UTC, rindibudiaramdhan commented on .codeclimate.yml
> +- "database/"
oh begitu? yang ini karena saya mengikuti di dokumentasi codeclimatenya kang.
apakah maksudnya tidak ada tanda `/`, sehingga langsung `database`?

2021-05-19 06:18 UTC, rindibudiaramdhan commented on app/Http/Controllers/API/v1/TrackController.php
> +        if ($request->route()->named('recommendation')) {
ini saya gabungkan karena dianggap duplikasi oleh codeclimate nya kang @ayocodingit 
minta solusi yang lebih baiknya kang

2021-05-19 06:27 UTC, aldidoanta approved these changes

2021-05-19 06:30 UTC, ayocodingit commented on .codeclimate.yml
> +- "database/"
Iya cukup nama foldernya aja kang

2021-05-19 06:45 UTC, ayocodingit commented on app/Http/Controllers/API/v1/TrackController.php
> +        if ($request->route()->named('recommendation')) {
kalau kasusnya untuk select  mah gpp duplikasi yang pakai array aja 
jadi misal 

> public $selectRecommendation = [
'logistic_realization_items.product_id as product_id',
'logistic_realization_items.product_name as product_name',
....
];

> public $selectNotRecommendation = [
'logistic_realization_items.final_product_id as product_id',
'logistic_realization_items.final_product_name as product_name',
...
];

kemudian buat function getSelectFullRecommendation 

> getSelectFullRecommendation 
return array_merge([
            DB::raw('IFNULL(logistic_realization_items.id, needs.id) as id'),
            'needs.id as need_id',
            'logistic_realization_items.id as realization_id',
            'logistic_realization_items.created_by',
            'products.category'
        ], $this->NameVariable

2021-05-19 06:45 UTC, ayocodingit commented on app/Http/Controllers/API/v1/TrackController.php
> +        if ($request->route()->named('recommendation')) {
coba gini kang @rindibudiaramdhan

2021-05-19 08:33 UTC, ayocodingit approved these changes

2021-05-19 10:50 UTC, merged