[ALKES] New Endpoint API Detail Logistic Request
jabardigitalservice/pikobar-logistik-api pull request #460
Opened 2022-10-26 03:30 UTC by imamdev93

### Overview
- API get detail logistic request
- API get list need
- API get list logistic realization items

<img width="462" alt="Screen Shot 2022-10-26 at 10 27 32" src="https://user-images.githubusercontent.com/63537236/197927674-152e721c-d8b9-4306-b570-e7659da69496.png">

### Related Issue
https://app.clickup.com/t/2y869m6

### Evidence
-title: [ALKES] New Endpoint API Detail Logistic Request
-project: Pikobar Logistik
-participants: @imamdev93

2022-10-26 03:34 UTC, rindibudiaramdhan commented on app/Traits/SelectTrait.php
> +    public function selectRecommendationSalur()
```suggestion
    public function selectRecommendation()
```

2022-10-26 03:35 UTC, rindibudiaramdhan commented on app/Traits/SelectTrait.php
> +    public function selectRecommendationSalur()
tetap di set ke english ya

2022-10-26 03:37 UTC, rindibudiaramdhan commented on routes/api.php
> +        Route::get('/logistic-request/detail/{id}', 'LogisticRequestController@detail');
tidak di `v2` kan saja mang @imamdev93 ?
karena tujuannya sama seperti endpoint `'/logistic-request/{id}'` kan ya?

2022-10-26 03:40 UTC, rindibudiaramdhan reviewed
kenapa dijadikan trait mang @imamdev93 ?

2022-10-26 04:36 UTC, imamdev93 commented on app/Traits/SelectTrait.php
> +    public function selectRecommendationSalur()
oke disini mang [3744680](https://github.com/jabardigitalservice/pikobar-logistik-api/pull/460/commits/37446804efa8da1c4886a4a1af97c9780122049d)

2022-10-26 04:36 UTC, imamdev93 commented on routes/api.php
> +        Route::get('/logistic-request/detail/{id}', 'LogisticRequestController@detail');
iyah tujuannya sama, apa baiknya di jadiin ke v2 aja?

2022-10-26 04:37 UTC, imamdev93 commented on app/Traits/SelectTrait.php
> +    public function selectRecommendationSalur()
> kenapa dijadikan trait mang @imamdev93 ?

karena di pakai lebih dari satu function mang untuk trait `SelectTrait` sama `TransformTrait` .

2022-10-26 04:46 UTC, rindibudiaramdhan commented on routes/api.php
> +        Route::get('/logistic-request/detail/{id}', 'LogisticRequestController@detail');
saran saya sih gitu kang. karena tujuannya sama tetapi tidak ingin mengganggu versi sebelumnya

2022-10-26 04:55 UTC, imamdev93 commented on app/Traits/SelectTrait.php
> +    public function selectRecommendationSalur()
> kenapa dijadikan trait mang @imamdev93 ?

karena di pakai lebih dari satu function mang untuk trait SelectTrait sama TransformTrait .

2022-10-26 05:53 UTC, sandisunandar99 commented on routes/api.php
> +        Route::get('/logistic-request/detail/{id}', 'LogisticRequestController@detail');
nah setuju sih baiknya mah ketika enpointnya sama tapi dengan output data yang berbeda bisa d jadiin v2
.. cuman yg jadi pertanyaan yg v1 belum di jadiin prifix v1 ya?

2022-10-26 06:01 UTC, imamdev93 commented on routes/api.php
> +        Route::get('/logistic-request/detail/{id}', 'LogisticRequestController@detail');
yang v1 udah pake prefix kang @sandisunandar99.

2022-10-26 07:19 UTC, imamdev93 commented on routes/api.php
> +        Route::get('/logistic-request/detail/{id}', 'LogisticRequestController@detail');
nah mau tanya juga sih untuk versioning API ini apakah ada referensi nya ga ya misal dari v1 ke v2? apa perbedaanya gitu

2022-10-26 08:10 UTC, rindibudiaramdhan commented on routes/api.php
> +        Route::get('/logistic-request/detail/{id}', 'LogisticRequestController@detail');
perbedaan kyk gimana nya kang? di postman nya ya?

2022-10-26 08:14 UTC, rindibudiaramdhan commented on app/Traits/SelectTrait.php
> +    public function selectRecommendationSalur()
preferensi saya ga ke Trait sih. ada solusi lain ga ya? misal di modelnya?

2022-10-26 08:18 UTC, sandisunandar99 commented on routes/api.php
> +        Route::get('/logistic-request/detail/{id}', 'LogisticRequestController@detail');
oh udah ,, sip ath harusnya klo bgitu mah

2022-10-26 08:18 UTC, sandisunandar99 approved these changes

2022-10-26 08:23 UTC, ayocodingit requested changes

2022-10-26 08:23 UTC, ayocodingit commented on app/Http/Resources/LogisticAdminRealizationResource.php
> +     * Transform the resource into an array.
kenapa ini ada paginate limit yah kang, sebaikknya di simpan di controller yah, resource itu baiknya untuk maping response  saja

2022-10-27 03:03 UTC, rindibudiaramdhan approved these changes

2022-10-27 03:04 UTC, ayocodingit approved these changes

2022-10-27 03:42 UTC, merged